import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// We need translations for all UI text.
const resources = {
  en: {
    translation: {
      nav: { voice_command: "Voice Command", settings: "Settings", logout: "Logout" },
      dashboard: { farm_overview: "FARM<br/>OVERVIEW", welcome: "Welcome back, Developer", location: "Location", loading_forecast: "Loading Local Forecast", weather: "WEATHER", irrigation_advice: "Irrigation Advice", irrigation_advice_delay: "Delay watering for 24-48 hours. Rain is likely in this forecast window.", irrigation_advice_light: "Use light irrigation and check soil moisture before watering deeply.", irrigation_advice_normal: "Water on the next cool morning or evening if the top soil feels dry.", forecast_3day: "3-Day Forecast", market_price: "MARKET PRICE", market_desc: "AI prediction based on current market trends and historical data.", view_report: "View Full Report", current_price: "Current Price", next_month: "Next Month (Est)", qtl: "Qtl", hold: "Hold", sell_now: "Sell Now", scan_crop: "SCAN CROP", scan_desc: "Upload leaf image to analyze disease", analyze: "Analyze Now", analyzing: "Analyzing...", drop_image: "Drop image here or click to browse", banner_title: "Tell Us About Your Farm", banner_desc: "Please describe what you are farming and the size of your land so we can personalize your dashboard.", banner_placeholder: "e.g., I farm 5 acres of wheat and rice...", submit_text: "Submit Text", saving: "Saving...", stop_recording: "Stop Recording", record_voice: "Record Voice", recording_speak: "Recording... Speak now.", processing_ai: "Processing with AI...", use_camera: "Use Camera", remove_image: "Remove Image", refresh_prices: "Refresh Prices", refreshing: "Refreshing...", last_fetched: "Last Fetched", ai_analysis: "AI Analysis" },
      settings: { title: "FARMER SETTINGS", language: "Language", land_size: "Land Size Unit", primary_crop: "Primary Crop", save: "Save Preferences", acres: "Acres", hectares: "Hectares", bigha: "Bigha", wheat: "Wheat", rice: "Rice", sugarcane: "Sugarcane", cotton: "Cotton", farm_desc_label: "Farm Description (Processed by AI)", farm_desc_hint: "Update your farm description to automatically detect crops and land size.", farm_desc_placeholder: "E.g., I grow wheat on 5 acres of land...", toast_pref_success: "Preferences saved successfully!", toast_pref_error: "Error saving preferences.", toast_voice_success: "Voice description processed and saved successfully!", toast_voice_fail: "Failed to process voice.", toast_voice_error: "Error submitting voice.", toast_mic_error: "Could not access microphone.", guntha: "Guntha", biswa: "Biswa", kanal: "Kanal", marla: "Marla", cent: "Cent", maize: "Maize", pearl_millet: "Pearl Millet / Bajra", sorghum: "Sorghum / Jowar", mustard: "Mustard", groundnut: "Groundnut / Peanut", chickpea: "Chickpea / Gram", soybean: "Soybean", back: "Back", use_voice: "Use Voice", stop_recording: "Stop Recording" },
      report: { loading: "Loading Report...", title: "Full Market Report", primary_crop: "Primary Crop:", current_price: "Current Price:", predicted_price: "Predicted Price Next Month:", system_advice: "System Advice:", historical_trends: "Historical Trends", chart_placeholder: "[Chart Placeholder: Implement Chart.js or Recharts here in future]", close_report: "Close Report" },
      weather: { 0: 'Clear Sky', 1: 'Mainly Clear', 2: 'Partly Cloudy', 3: 'Overcast', 45: 'Foggy', 48: 'Rime Fog', 51: 'Light Drizzle', 53: 'Drizzle', 55: 'Heavy Drizzle', 61: 'Light Rain', 63: 'Rain', 65: 'Heavy Rain', 71: 'Light Snow', 73: 'Snow', 75: 'Heavy Snow', 80: 'Rain Showers', 81: 'Heavy Showers', 82: 'Violent Showers', 95: 'Thunderstorm', 96: 'Thunderstorm With Hail', 99: 'Severe Thunderstorm' }
    }
  },
  hi: {
    translation: {
      nav: { voice_command: "आवाज़ कमांड", settings: "सेटिंग्स", logout: "लॉग आउट" },
      dashboard: { farm_overview: "खेत का<br/>विवरण", welcome: "वापसी पर स्वागत है, डेवलपर", location: "स्थान", loading_forecast: "मौसम की जानकारी लोड हो रही है", weather: "मौसम", irrigation_advice: "सिंचाई सलाह", irrigation_advice_delay: "24-48 घंटों के लिए पानी देना रोकें। इस दौरान बारिश की संभावना है।", irrigation_advice_light: "हल्की सिंचाई का उपयोग करें और गहराई से पानी देने से पहले मिट्टी की नमी की जांच करें।", irrigation_advice_normal: "यदि ऊपरी मिट्टी सूखी लगे तो अगली ठंडी सुबह या शाम को पानी दें।", forecast_3day: "3-दिन का पूर्वानुमान", market_price: "बाज़ार मूल्य", market_desc: "वर्तमान बाजार के रुझानों और ऐतिहासिक डेटा के आधार पर एआई भविष्यवाणी।", view_report: "पूरी रिपोर्ट देखें", current_price: "वर्तमान मूल्य", next_month: "अगले महीने (अनुमानित)", qtl: "क्विंटल", hold: "रखें", sell_now: "अभी बेचें", scan_crop: "फसल स्कैन", scan_desc: "बीमारी का विश्लेषण करने के लिए पत्ती की छवि अपलोड करें", analyze: "अभी विश्लेषण करें", analyzing: "विश्लेषण हो रहा है...", drop_image: "छवि यहां छोड़ें या ब्राउज़ करने के लिए क्लिक करें", banner_title: "हमें अपने खेत के बारे में बताएं", banner_desc: "कृपया बताएं कि आप क्या खेती कर रहे हैं और आपकी जमीन का आकार क्या है ताकि हम आपके डैशबोर्ड को वैयक्तिकृत कर सकें।", banner_placeholder: "उदा., मैं 5 एकड़ में गेहूं और चावल की खेती करता हूं...", submit_text: "टेक्स्ट सबमिट करें", saving: "सहेजा जा रहा है...", stop_recording: "रिकॉर्डिंग रोकें", record_voice: "आवाज़ रिकॉर्ड करें", recording_speak: "रिकॉर्ड हो रहा है... अब बोलें।", processing_ai: "एआई के साथ संसाधित हो रहा है...", use_camera: "कैमरा का उपयोग करें", remove_image: "छवि निकालें", refresh_prices: "मूल्य ताज़ा करें", refreshing: "ताज़ा किया जा रहा है...", last_fetched: "अंतिम बार प्राप्त", ai_analysis: "एआई विश्लेषण" },
      settings: { title: "किसान सेटिंग्स", language: "भाषा", land_size: "भूमि का आकार इकाई", primary_crop: "प्राथमिक फसल", save: "प्राथमिकताएं सहेजें", acres: "एकड़", hectares: "हेक्टेयर", bigha: "बीघा", wheat: "गेहूं", rice: "चावल", sugarcane: "गन्ना", cotton: "कपास", farm_desc_label: "खेत का विवरण (एआई द्वारा संसाधित)", farm_desc_hint: "फसलों और भूमि के आकार का स्वचालित रूप से पता लगाने के लिए अपने खेत के विवरण को अपडेट करें।", farm_desc_placeholder: "उदा., मैं 5 एकड़ जमीन पर गेहूं उगाता हूं...", toast_pref_success: "प्राथमिकताएं सफलतापूर्वक सहेजी गईं!", toast_pref_error: "प्राथमिकताएं सहेजने में त्रुटि।", toast_voice_success: "वॉयस विवरण सफलतापूर्वक संसाधित और सहेजा गया!", toast_voice_fail: "आवाज़ संसाधित करने में विफल।", toast_voice_error: "आवाज़ सबमिट करने में त्रुटि।", toast_mic_error: "माइक्रोफ़ोन तक नहीं पहुंच सका।", guntha: "गुंठा", biswa: "बिस्वा", kanal: "कनाल", marla: "मरला", cent: "सेंट", maize: "मक्का", pearl_millet: "बाजरा", sorghum: "ज्वार", mustard: "सरसों", groundnut: "मूंगफली", chickpea: "चना", soybean: "सोयाबीन", back: "वापस", use_voice: "आवाज़ का उपयोग करें", stop_recording: "रिकॉर्डिंग रोकें" },
      report: { loading: "रिपोर्ट लोड हो रही है...", title: "पूर्ण बाज़ार रिपोर्ट", primary_crop: "प्राथमिक फसल:", current_price: "वर्तमान मूल्य:", predicted_price: "अगले महीने का अनुमानित मूल्य:", system_advice: "सिस्टम सलाह:", historical_trends: "ऐतिहासिक रुझान", chart_placeholder: "[चार्ट प्लेसहोल्डर: भविष्य में यहां Chart.js या Recharts लागू करें]", close_report: "रिपोर्ट बंद करें" },
      weather: { 0: 'साफ आसमान', 1: 'मुख्य रूप से साफ', 2: 'आंशिक रूप से बादल', 3: 'बादल छाए रहेंगे', 45: 'धुंध', 48: 'पाले वाली धुंध', 51: 'हल्की बूंदाबांदी', 53: 'बूंदाबांदी', 55: 'भारी बूंदाबांदी', 61: 'हल्की बारिश', 63: 'बारिश', 65: 'भारी बारिश', 71: 'हल्की बर्फबारी', 73: 'बर्फबारी', 75: 'भारी बर्फबारी', 80: 'बारिश की बौछारें', 81: 'भारी बौछारें', 82: 'भयंकर बौछारें', 95: 'आंधी', 96: 'ओलों के साथ आंधी', 99: 'भयंकर आंधी' }
    }
  },
  mr: {
    translation: {
      nav: { voice_command: "आवाज कमांड", settings: "सेटिंग्ज", logout: "लॉगआउट" },
      dashboard: { farm_overview: "शेती<br/>आढावा", welcome: "परत स्वागत आहे, डेव्हलपर", location: "ठिकाण", loading_forecast: "हवामान माहिती लोड होत आहे", weather: "हवामान", irrigation_advice: "सिंचन सल्ला", irrigation_advice_delay: "२४-४८ तास पाणी देणे थांबवा. या दरम्यान पाऊस पडण्याची शक्यता आहे.", irrigation_advice_light: "हलके सिंचन वापरा आणि जास्त पाणी देण्यापूर्वी मातीतील ओलावा तपासा.", irrigation_advice_normal: "जर वरची माती कोरडी वाटत असेल तर पुढील थंड सकाळी किंवा संध्याकाळी पाणी द्या.", forecast_3day: "३-दिवसांचा अंदाज", market_price: "बाजार भाव", market_desc: "सध्याचे बाजारातील कल आणि ऐतिहासिक डेटावर आधारित AI अंदाज.", view_report: "संपूर्ण अहवाल पहा", current_price: "सध्याचा भाव", next_month: "पुढील महिना (अंदाज)", qtl: "क्विंटल", hold: "थांबा", sell_now: "आता विका", scan_crop: "पीक स्कॅन करा", scan_desc: "रोगाचे विश्लेषण करण्यासाठी पानाचा फोटो अपलोड करा", analyze: "आता विश्लेषण करा", analyzing: "विश्लेषण करत आहे...", drop_image: "इथे फोटो टाका किंवा ब्राउझ करण्यासाठी क्लिक करा", banner_title: "आम्हाला तुमच्या शेतीबद्दल सांगा", banner_desc: "कृपया तुम्ही कशाची शेती करत आहात आणि तुमच्या जमिनीचा आकार काय आहे ते सांगा जेणेकरून आम्ही तुमचा डॅशबोर्ड वैयक्तिकृत करू शकू.", banner_placeholder: "उदा., मी ५ एकरवर गहू आणि तांदूळ पिकवतो...", submit_text: "मजकूर सबमिट करा", saving: "जतन करत आहे...", stop_recording: "रेकॉर्डिंग थांबवा", record_voice: "आवाज रेकॉर्ड करा", recording_speak: "रेकॉर्ड करत आहे... आता बोला.", processing_ai: "AI सोबत प्रक्रिया करत आहे...", use_camera: "कॅमेरा वापरा", remove_image: "प्रतिमा काढा", refresh_prices: "किमती रिफ्रेश करा", refreshing: "रिफ्रेश करत आहे...", last_fetched: "शेवटचे प्राप्त केले", ai_analysis: "एआय विश्लेषण" },
      settings: { title: "शेतकरी सेटिंग्ज", language: "भाषा", land_size: "जमिनीचे एकक", primary_crop: "मुख्य पीक", save: "सेटिंग्ज जतन करा", acres: "एकर", hectares: "हेक्टर", bigha: "बिघा", wheat: "गहू", rice: "तांदूळ", sugarcane: "ऊस", cotton: "कापूस", farm_desc_label: "शेतीचे वर्णन (AI द्वारे प्रक्रिया केलेले)", farm_desc_hint: "पिके आणि जमिनीचा आकार आपोआप ओळखण्यासाठी तुमच्या शेतीचे वर्णन अपडेट करा.", farm_desc_placeholder: "उदा., मी ५ एकर जागेवर गहू पिकवतो...", toast_pref_success: "सेटिंग्ज यशस्वीरित्या जतन केल्या!", toast_pref_error: "सेटिंग्ज जतन करताना त्रुटी.", toast_voice_success: "आवाज वर्णन यशस्वीरित्या प्रक्रिया आणि जतन केले!", toast_voice_fail: "आवाज प्रक्रिया करण्यात अयशस्वी.", toast_voice_error: "आवाज पाठवताना त्रुटी.", toast_mic_error: "मायक्रोफोनमध्ये प्रवेश करू शकलो नाही.", guntha: "गुंठा", biswa: "बिस्वा", kanal: "कनाल", marla: "मरला", cent: "सेंट", maize: "मका", pearl_millet: "बाजरी", sorghum: "ज्वारी", mustard: "मोहरी", groundnut: "भुईमूग", chickpea: "हरभरा", soybean: "सोयाबीन", back: "मागे", use_voice: "आवाजाचा वापर करा", stop_recording: "रेकॉर्डिंग थांबवा" },
      report: { loading: "अहवाल लोड होत आहे...", title: "संपूर्ण बाजार अहवाल", primary_crop: "मुख्य पीक:", current_price: "सध्याचा भाव:", predicted_price: "पुढील महिन्याचा अंदाजित भाव:", system_advice: "सिस्टम सल्ला:", historical_trends: "ऐतिहासिक कल", chart_placeholder: "[चार्ट प्लेसहोल्डर: भविष्यात येथे Chart.js किंवा Recharts लागू करा]", close_report: "अहवाल बंद करा" },
      weather: { 0: 'निरभ्र आकाश', 1: 'मुख्यत्वे निरभ्र', 2: 'अंशतः ढगाळ', 3: 'ढगाळ', 45: 'धुके', 48: 'गोठवणारे धुके', 51: 'हलकी रिमझिम', 53: 'रिमझिम पाऊस', 55: 'जोरदार रिमझिम', 61: 'हलका पाऊस', 63: 'पाऊस', 65: 'मुसळधार पाऊस', 71: 'हलकी बर्फवृष्टी', 73: 'बर्फवृष्टी', 75: 'जोरदार बर्फवृष्टी', 80: 'पावसाच्या सरी', 81: 'जोरदार सरी', 82: 'भयंकर सरी', 95: 'वादळ', 96: 'गारांसह वादळ', 99: 'तीव्र वादळ' }
    }
  },
  pa: {
    translation: {
      nav: { voice_command: "ਆਵਾਜ਼ ਕਮਾਂਡ", settings: "ਸੈਟਿੰਗਾਂ", logout: "ਲੌਗਆਊਟ" },
      dashboard: { farm_overview: "ਖੇਤ<br/>ਸੰਖੇਪ", welcome: "ਵਾਪਸੀ ਤੇ ਸਵਾਗਤ ਹੈ, ਡਿਵੈਲਪਰ", location: "ਸਥਾਨ", loading_forecast: "ਮੌਸਮ ਜਾਣਕਾਰੀ ਲੋਡ ਹੋ ਰਹੀ ਹੈ", weather: "ਮੌਸਮ", irrigation_advice: "ਸਿੰਚਾਈ ਸਲਾਹ", irrigation_advice_delay: "24-48 ਘੰਟਿਆਂ ਲਈ ਪਾਣੀ ਦੇਣਾ ਰੋਕੋ। ਇਸ ਦੌਰਾਨ ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ ਹੈ।", irrigation_advice_light: "ਹਲਕੀ ਸਿੰਚਾਈ ਦੀ ਵਰਤੋਂ ਕਰੋ ਅਤੇ ਡੂੰਘਾਈ ਨਾਲ ਪਾਣੀ ਦੇਣ ਤੋਂ ਪਹਿਲਾਂ ਮਿੱਟੀ ਦੀ ਨਮੀ ਦੀ ਜਾਂਚ ਕਰੋ।", irrigation_advice_normal: "ਜੇਕਰ ਉੱਪਰਲੀ ਮਿੱਟੀ ਸੁੱਕੀ ਲੱਗੇ ਤਾਂ ਅਗਲੀ ਠੰਡੀ ਸਵੇਰ ਜਾਂ ਸ਼ਾਮ ਨੂੰ ਪਾਣੀ ਦਿਓ।", forecast_3day: "3-ਦਿਨਾਂ ਦੀ ਭਵਿੱਖਬਾਣੀ", market_price: "ਬਾਜ਼ਾਰ ਕੀਮਤ", market_desc: "ਮੌਜੂਦਾ ਬਾਜ਼ਾਰ ਦੇ ਰੁਝਾਨਾਂ ਅਤੇ ਇਤਿਹਾਸਕ ਡੇਟਾ 'ਤੇ ਅਧਾਰਤ AI ਭਵਿੱਖਬਾਣੀ।", view_report: "ਪੂਰੀ ਰਿਪੋਰਟ ਦੇਖੋ", current_price: "ਮੌਜੂਦਾ ਕੀਮਤ", next_month: "ਅਗਲੇ ਮਹੀਨੇ (ਅਨੁਮਾਨਿਤ)", qtl: "ਕੁਇੰਟਲ", hold: "ਰੱਖੋ", sell_now: "ਹੁਣ ਵੇਚੋ", scan_crop: "ਫਸਲ ਸਕੈਨ ਕਰੋ", scan_desc: "ਬਿਮਾਰੀ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਨ ਲਈ ਪੱਤੇ ਦੀ ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ", analyze: "ਹੁਣ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ", analyzing: "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...", drop_image: "ਤਸਵੀਰ ਇੱਥੇ ਛੱਡੋ ਜਾਂ ਬ੍ਰਾਊਜ਼ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ", banner_title: "ਸਾਨੂੰ ਆਪਣੇ ਖੇਤ ਬਾਰੇ ਦੱਸੋ", banner_desc: "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਕੀ ਖੇਤੀ ਕਰ ਰਹੇ ਹੋ ਅਤੇ ਤੁਹਾਡੀ ਜ਼ਮੀਨ ਦਾ ਆਕਾਰ ਕੀ ਹੈ ਤਾਂ ਜੋ ਅਸੀਂ ਤੁਹਾਡੇ ਡੈਸ਼ਬੋਰਡ ਨੂੰ ਵਿਅਕਤੀਗਤ ਬਣਾ ਸਕੀਏ।", banner_placeholder: "ਉਦਾਹਰਨ ਲਈ, ਮੈਂ 5 ਏਕੜ ਵਿੱਚ ਕਣਕ ਅਤੇ ਚਾਵਲ ਦੀ ਖੇਤੀ ਕਰਦਾ ਹਾਂ...", submit_text: "ਟੈਕਸਟ ਜਮ੍ਹਾਂ ਕਰੋ", saving: "ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...", stop_recording: "ਰਿਕਾਰਡਿੰਗ ਰੋਕੋ", record_voice: "ਆਵਾਜ਼ ਰਿਕਾਰਡ ਕਰੋ", recording_speak: "ਰਿਕਾਰਡ ਹੋ ਰਿਹਾ ਹੈ... ਹੁਣ ਬੋਲੋ।", processing_ai: "AI ਨਾਲ ਪ੍ਰਕਿਰਿਆ ਹੋ ਰਹੀ ਹੈ...", use_camera: "ਕੈਮਰਾ ਵਰਤੋ", remove_image: "ਚਿੱਤਰ ਹਟਾਓ", refresh_prices: "ਕੀਮਤਾਂ ਤਾਜ਼ਾ ਕਰੋ", refreshing: "ਤਾਜ਼ਾ ਹੋ ਰਿਹਾ ਹੈ...", last_fetched: "ਆਖਰੀ ਵਾਰ ਪ੍ਰਾਪਤ ਕੀਤਾ", ai_analysis: "ਏਆਈ ਵਿਸ਼ਲੇਸ਼ਣ" },
      settings: { title: "ਕਿਸਾਨ ਸੈਟਿੰਗਾਂ", language: "ਭਾਸ਼ਾ", land_size: "ਜ਼ਮੀਨ ਦਾ ਆਕਾਰ ਇਕਾਈ", primary_crop: "ਮੁੱਖ ਫਸਲ", save: "ਤਰਜੀਹਾਂ ਸੁਰੱਖਿਅਤ ਕਰੋ", acres: "ਏਕੜ", hectares: "ਹੈਕਟੇਅਰ", bigha: "ਬਿੱਘਾ", wheat: "ਕਣਕ", rice: "ਚਾਵਲ", sugarcane: "ਗੰਨਾ", cotton: "ਕਪਾਹ", farm_desc_label: "ਖੇਤ ਦਾ ਵੇਰਵਾ (AI ਦੁਆਰਾ ਪ੍ਰੋਸੈਸ ਕੀਤਾ ਗਿਆ)", farm_desc_hint: "ਫਸਲਾਂ ਅਤੇ ਜ਼ਮੀਨ ਦੇ ਆਕਾਰ ਦਾ ਆਪਣੇ ਆਪ ਪਤਾ ਲਗਾਉਣ ਲਈ ਆਪਣੇ ਖੇਤ ਦੇ ਵੇਰਵੇ ਨੂੰ ਅੱਪਡੇਟ ਕਰੋ।", farm_desc_placeholder: "ਉਦਾਹਰਨ ਲਈ, ਮੈਂ 5 ਏਕੜ ਜ਼ਮੀਨ 'ਤੇ ਕਣਕ ਉਗਾਉਂਦਾ ਹਾਂ...", toast_pref_success: "ਤਰਜੀਹਾਂ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਕੀਤੀਆਂ ਗਈਆਂ!", toast_pref_error: "ਤਰਜੀਹਾਂ ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰਨ ਵਿੱਚ ਤਰੁੱਟੀ।", toast_voice_success: "ਆਵਾਜ਼ ਦਾ ਵੇਰਵਾ ਸਫਲਤਾਪੂਰਵਕ ਪ੍ਰੋਸੈਸ ਅਤੇ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਗਿਆ!", toast_voice_fail: "ਆਵਾਜ਼ 'ਤੇ ਕਾਰਵਾਈ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।", toast_voice_error: "ਆਵਾਜ਼ ਜਮ੍ਹਾਂ ਕਰਨ ਵਿੱਚ ਤਰੁੱਟੀ।", toast_mic_error: "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਤੱਕ ਪਹੁੰਚ ਨਹੀਂ ਕੀਤੀ ਜਾ ਸਕੀ।", guntha: "ਗੁੰਠਾ", biswa: "ਬਿਸਵਾ", kanal: "ਕਨਾਲ", marla: "ਮਰਲਾ", cent: "ਸੈਂਟ", maize: "ਮੱਕੀ", pearl_millet: "ਬਾਜਰਾ", sorghum: "ਜਵਾਰ", mustard: "ਸਰ੍ਹੋਂ", groundnut: "ਮੂੰਗਫਲੀ", chickpea: "ਛੋਲੇ", soybean: "ਸੋਇਆਬੀਨ", back: "ਪਿੱਛੇ", use_voice: "ਆਵਾਜ਼ ਦੀ ਵਰਤੋਂ ਕਰੋ", stop_recording: "ਰਿਕਾਰਡਿੰਗ ਰੋਕੋ" },
      report: { loading: "ਰਿਪੋਰਟ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...", title: "ਪੂਰੀ ਬਾਜ਼ਾਰ ਰਿਪੋਰਟ", primary_crop: "ਮੁੱਖ ਫਸਲ:", current_price: "ਮੌਜੂਦਾ ਕੀਮਤ:", predicted_price: "ਅਗਲੇ ਮਹੀਨੇ ਦੀ ਅਨੁਮਾਨਿਤ ਕੀਮਤ:", system_advice: "ਸਿਸਟਮ ਸਲਾਹ:", historical_trends: "ਇਤਿਹਾਸਕ ਰੁਝਾਨ", chart_placeholder: "[ਚਾਰਟ ਪਲੇਸਹੋਲਡਰ: ਭਵਿੱਖ ਵਿੱਚ ਇੱਥੇ Chart.js ਜਾਂ Recharts ਲਾਗੂ ਕਰੋ]", close_report: "ਰਿਪੋਰਟ ਬੰਦ ਕਰੋ" },
      weather: { 0: 'ਸਾਫ ਅਸਮਾਨ', 1: 'ਮੁੱਖ ਤੌਰ ਤੇ ਸਾਫ', 2: 'ਅੰਸ਼ਕ ਤੌਰ ਤੇ ਬੱਦਲ', 3: 'ਬੱਦਲਵਾਈ', 45: 'ਧੁੰਦ', 48: 'ਪਾਲੇ ਵਾਲੀ ਧੁੰਦ', 51: 'ਹਲਕੀ ਬੂੰਦਾਬਾਂਦੀ', 53: 'ਬੂੰਦਾਬਾਂਦੀ', 55: 'ਭਾਰੀ ਬੂੰਦਾਬਾਂਦੀ', 61: 'ਹਲਕੀ ਬਾਰਿਸ਼', 63: 'ਬਾਰਿਸ਼', 65: 'ਭਾਰੀ ਬਾਰਿਸ਼', 71: 'ਹਲਕੀ ਬਰਫਬਾਰੀ', 73: 'ਬਰਫਬਾਰੀ', 75: 'ਭਾਰੀ ਬਰਫਬਾਰੀ', 80: 'ਬਾਰਿਸ਼ ਦੀਆਂ ਬੌਛਾਰਾਂ', 81: 'ਭਾਰੀ ਬੌਛਾਰਾਂ', 82: 'ਭਿਆਨਕ ਬੌਛਾਰਾਂ', 95: 'ਤੂਫ਼ਾਨ', 96: 'ਗੜੇਮਾਰੀ ਨਾਲ ਤੂਫ਼ਾਨ', 99: 'ਭਿਆਨਕ ਤੂਫ਼ਾਨ' }
    }
  },
  te: {
    translation: {
      nav: { voice_command: "వాయిస్ కమాండ్", settings: "సెట్టింగ్‌లు", logout: "లాగ్అవుట్" },
      dashboard: { farm_overview: "పొలం<br/>అవలోకనం", welcome: "తిరిగి స్వాగతం, డెవలపర్", location: "ప్రదేశం", loading_forecast: "వాతావరణ సమాచారం లోడ్ అవుతోంది", weather: "వాతావరణం", irrigation_advice: "నీటిపారుదల సలహా", irrigation_advice_delay: "24-48 గంటల పాటు నీరు పెట్టడం ఆపండి. ఈ సమయంలో వర్షం వచ్చే అవకాశం ఉంది.", irrigation_advice_light: "తేలికపాటి నీటిపారుదల ఉపయోగించండి మరియు ఎక్కువగా నీరు పెట్టే ముందు మట్టి తేమను తనిఖీ చేయండి.", irrigation_advice_normal: "పై మట్టి పొడిగా అనిపిస్తే తదుపరి చల్లని ఉదయం లేదా సాయంత్రం నీరు పెట్టండి.", forecast_3day: "3-రోజుల సూచన", market_price: "మార్కెట్ ధర", market_desc: "ప్రస్తుత మార్కెట్ పోకడలు మరియు చారిత్రక డేటా ఆధారంగా AI అంచనా.", view_report: "పూర్తి నివేదికను వీక్షించండి", current_price: "ప్రస్తుత ధర", next_month: "వచ్చే నెల (అంచనా)", qtl: "క్వింటాల్", hold: "ఉంచండి", sell_now: "ఇప్పుడే అమ్మండి", scan_crop: "పంటను స్కాన్ చేయండి", scan_desc: "వ్యాధిని విశ్లేషించడానికి ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి", analyze: "ఇప్పుడే విశ్లేషించండి", analyzing: "విశ్లేషిస్తోంది...", drop_image: "చిత్రాన్ని ఇక్కడ వదలండి లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి", banner_title: "మీ పొలం గురించి మాకు చెప్పండి", banner_desc: "మేము మీ డాష్‌బోర్డ్‌ను వ్యక్తిగతీకరించడానికి దయచేసి మీరు ఏమి పండిస్తున్నారో మరియు మీ భూమి పరిమాణాన్ని వివరించండి.", banner_placeholder: "ఉదాహరణకు, నేను 5 ఎకరాల్లో గోధుమలు మరియు వరి సాగు చేస్తాను...", submit_text: "వచనాన్ని సమర్పించండి", saving: "సేవ్ చేస్తోంది...", stop_recording: "రికార్డింగ్ ఆపు", record_voice: "వాయిస్ రికార్డ్ చేయండి", recording_speak: "రికార్డ్ అవుతోంది... ఇప్పుడు మాట్లాడండి.", processing_ai: "AIతో ప్రాసెస్ అవుతోంది...", use_camera: "కెమెరాను ఉపయోగించండి", remove_image: "చిత్రాన్ని తీసివేయండి", refresh_prices: "ధరలను రిఫ్రెష్ చేయండి", refreshing: "రిఫ్రెష్ అవుతోంది...", last_fetched: "చివరిగా పొందినది", ai_analysis: "AI విశ్లేషణ" },
      settings: { title: "రైతు సెట్టింగ్‌లు", language: "భాష", land_size: "భూమి పరిమాణం యూనిట్", primary_crop: "ప్రధాన పంట", save: "ప్రాధాన్యతలను సేవ్ చేయండి", acres: "ఎకరాలు", hectares: "హెక్టార్లు", bigha: "బిఘా", wheat: "గోధుమ", rice: "వరి", sugarcane: "చెరకు", cotton: "పత్తి", farm_desc_label: "పొలం వివరణ (AI ద్వారా ప్రాసెస్ చేయబడింది)", farm_desc_hint: "పంటలు మరియు భూమి పరిమాణాన్ని స్వయంచాలకంగా గుర్తించడానికి మీ పొలం వివరణను అప్‌డేట్ చేయండి.", farm_desc_placeholder: "ఉదాహరణకు, నేను 5 ఎకరాల భూమిలో గోధుమ పండిస్తాను...", toast_pref_success: "ప్రాధాన్యతలు విజయవంతంగా సేవ్ చేయబడ్డాయి!", toast_pref_error: "ప్రాధాన్యతలను సేవ్ చేయడంలో లోపం.", toast_voice_success: "వాయిస్ వివరణ విజయవంతంగా ప్రాసెస్ చేయబడింది మరియు సేవ్ చేయబడింది!", toast_voice_fail: "వాయిస్ ప్రాసెస్ చేయడంలో విఫలమైంది.", toast_voice_error: "వాయిస్‌ను సమర్పించడంలో లోపం.", toast_mic_error: "మైక్రోఫోన్‌ను యాక్సెస్ చేయలేకపోయాము.", guntha: "గుంట", biswa: "బిస్వా", kanal: "కనాల్", marla: "మర్లా", cent: "సెంట్", maize: "మొక్కజొన్న", pearl_millet: "సజ్జలు", sorghum: "జొన్నలు", mustard: "ఆవాలు", groundnut: "వేరుశెనగ", chickpea: "శెనగలు", soybean: "సోయాబీన్", back: "వెనుకకు", use_voice: "వాయిస్ ఉపయోగించండి", stop_recording: "రికార్డింగ్ ఆపు" },
      report: { loading: "నివేదిక లోడ్ అవుతోంది...", title: "పూర్తి మార్కెట్ నివేదిక", primary_crop: "ప్రధాన పంట:", current_price: "ప్రస్తుత ధర:", predicted_price: "వచ్చే నెల అంచనా ధర:", system_advice: "సిస్టమ్ సలహా:", historical_trends: "చారిత్రక పోకడలు", chart_placeholder: "[చార్ట్ ప్లేస్‌హోల్డర్: భవిష్యత్తులో ఇక్కడ Chart.js లేదా Recharts అమలు చేయండి]", close_report: "నివేదికను మూసివేయండి" },
      weather: { 0: 'స్వచ్ఛమైన ఆకాశం', 1: 'ప్రధానంగా స్వచ్ఛంగా', 2: 'పాక్షికంగా మేఘావృతం', 3: 'మేఘావృతం', 45: 'పొగమంచు', 48: 'గడ్డకట్టే పొగమంచు', 51: 'తేలికపాటి చినుకులు', 53: 'చినుకులు', 55: 'భారీ చినుకులు', 61: 'తేలికపాటి వర్షం', 63: 'వర్షం', 65: 'భారీ వర్షం', 71: 'తేలికపాటి మంచు', 73: 'మంచు', 75: 'భారీ మంచు', 80: 'జల్లులు', 81: 'భారీ జల్లులు', 82: 'భయంకరమైన జల్లులు', 95: 'ఉరుములతో కూడిన గాలివాన', 96: 'వడగళ్లతో కూడిన గాలివాన', 99: 'తీవ్రమైన గాలివాన' }
    }
  },
  ta: {
    translation: {
      nav: { voice_command: "குரல் கட்டளை", settings: "அமைப்புகள்", logout: "வெளியேறு" },
      dashboard: { farm_overview: "பண்ணை<br/>கண்ணோட்டம்", welcome: "மீண்டும் வருக, டெவலப்பர்", location: "இடம்", loading_forecast: "வானிலை முன்னறிவிப்பு ஏற்றப்படுகிறது", weather: "வானிலை", irrigation_advice: "நீர்ப்பாசன ஆலோசனை", irrigation_advice_delay: "24-48 மணிநேரத்திற்கு நீர்ப்பாசனத்தை தாமதப்படுத்துங்கள். இந்த நேரத்தில் மழை பெய்ய வாய்ப்புள்ளது.", irrigation_advice_light: "லேசான நீர்ப்பாசனத்தைப் பயன்படுத்தவும், அதிகமாக நீர் பாய்ச்சுவதற்கு முன் மண்ணின் ஈரப்பதத்தை சரிபார்க்கவும்.", irrigation_advice_normal: "மேல் மண் வறண்டதாக உணர்ந்தால் அடுத்த குளிர்ந்த காலை அல்லது மாலையில் நீர் பாய்ச்சவும்.", forecast_3day: "3-நாள் முன்னறிவிப்பு", market_price: "சந்தை விலை", market_desc: "தற்போதைய சந்தை போக்குகள் மற்றும் வரலாற்று தரவுகளின் அடிப்படையில் AI கணிப்பு.", view_report: "முழு அறிக்கையை காண்க", current_price: "தற்போதைய விலை", next_month: "அடுத்த மாதம் (மதிப்பீடு)", qtl: "குவிண்டால்", hold: "வைத்திருங்கள்", sell_now: "இப்போதே விற்கவும்", scan_crop: "பயிரை ஸ்கேன் செய்", scan_desc: "நோயை பகுப்பாய்வு செய்ய இலை படத்தை பதிவேற்றவும்", analyze: "இப்போதே பகுப்பாய்வு செய்", analyzing: "பகுப்பாய்வு செய்யப்படுகிறது...", drop_image: "படத்தை இங்கே விடவும் அல்லது உலாவ கிளிக் செய்யவும்", banner_title: "உங்கள் பண்ணை பற்றி எங்களிடம் கூறுங்கள்", banner_desc: "உங்கள் டாஷ்போர்டை தனிப்பயனாக்க தயவுசெய்து நீங்கள் என்ன பயிரிடுகிறீர்கள் மற்றும் உங்கள் நிலத்தின் அளவை விவரிக்கவும்.", banner_placeholder: "எ.கா., நான் 5 ஏக்கரில் கோதுமை மற்றும் நெல் பயிரிடுகிறேன்...", submit_text: "உரையை சமர்ப்பிக்கவும்", saving: "சேமிக்கிறது...", stop_recording: "பதிவு செய்வதை நிறுத்து", record_voice: "குரலை பதிவு செய்", recording_speak: "பதிவு செய்யப்படுகிறது... இப்போது பேசுங்கள்.", processing_ai: "AI உடன் செயலாக்கப்படுகிறது...", use_camera: "கேமராவைப் பயன்படுத்தவும்", remove_image: "படத்தை அகற்று", refresh_prices: "விலைகளை புதுப்பிக்கவும்", refreshing: "புதுப்பிக்கிறது...", last_fetched: "கடைசியாக பெறப்பட்டது", ai_analysis: "AI பகுப்பாய்வு" },
      settings: { title: "விவசாயி அமைப்புகள்", language: "மொழி", land_size: "நில அளவை அலகு", primary_crop: "முதன்மை பயிர்", save: "விருப்பங்களை சேமி", acres: "ஏக்கர்", hectares: "ஹெக்டேர்", bigha: "பிகா", wheat: "கோதுமை", rice: "அரிசி", sugarcane: "கரும்பு", cotton: "பருத்தி", farm_desc_label: "பண்ணை விளக்கம் (AI ஆல் செயலாக்கப்பட்டது)", farm_desc_hint: "பயிர்கள் மற்றும் நிலத்தின் அளவை தானாகவே கண்டறிய உங்கள் பண்ணை விளக்கத்தை புதுப்பிக்கவும்.", farm_desc_placeholder: "எ.கா., நான் 5 ஏக்கர் நிலத்தில் கோதுமை பயிரிடுகிறேன்...", toast_pref_success: "விருப்பங்கள் வெற்றிகரமாக சேமிக்கப்பட்டன!", toast_pref_error: "விருப்பங்களை சேமிப்பதில் பிழை.", toast_voice_success: "குரல் விளக்கம் வெற்றிகரமாக செயலாக்கப்பட்டு சேமிக்கப்பட்டது!", toast_voice_fail: "குரலை செயலாக்க முடியவில்லை.", toast_voice_error: "குரலை சமர்ப்பிப்பதில் பிழை.", toast_mic_error: "மைக்ரோஃபோனை அணுக முடியவில்லை.", guntha: "குண்டா", biswa: "பிஸ்வா", kanal: "கனால்", marla: "மர்லா", cent: "சென்ட்", maize: "மக்காச்சோளம்", pearl_millet: "கம்பு", sorghum: "சோளம்", mustard: "கடுகு", groundnut: "நிலக்கடலை", chickpea: "கொண்டைக்கடலை", soybean: "சோயாபீன்", back: "பின்னால்", use_voice: "குரலைப் பயன்படுத்துங்கள்", stop_recording: "பதிவு செய்வதை நிறுத்து" },
      report: { loading: "அறிக்கை ஏற்றப்படுகிறது...", title: "முழு சந்தை அறிக்கை", primary_crop: "முதன்மை பயிர்:", current_price: "தற்போதைய விலை:", predicted_price: "அடுத்த மாத கணிக்கப்பட்ட விலை:", system_advice: "கணினி ஆலோசனை:", historical_trends: "வரலாற்றுப் போக்குகள்", chart_placeholder: "[விளக்கப்பட இடப்பிடிப்பான்: எதிர்காலத்தில் இங்கே Chart.js அல்லது Recharts ஐச் செயல்படுத்தவும்]", close_report: "அறிக்கையை மூடு" },
      weather: { 0: 'தெளிவான வானம்', 1: 'முக்கியமாக தெளிவானது', 2: 'பகுதி மேகமூட்டம்', 3: 'மேகமூட்டம்', 45: 'மூடுபனி', 48: 'உறைபனி மூடுபனி', 51: 'லேசான தூறல்', 53: 'தூறல்', 55: 'கனமான தூறல்', 61: 'லேசான மழை', 63: 'மழை', 65: 'கனமழை', 71: 'லேசான பனி', 73: 'பனி', 75: 'கடுமையான பனி', 80: 'மழை தூறல்', 81: 'கனமான தூறல்', 82: 'கடுமையான தூறல்', 95: 'இடியுடன் கூடிய மழை', 96: 'ஆலங்கட்டியுடன் கூடிய மழை', 99: 'கடுமையான இடியுடன் கூடிய மழை' }
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false, // react already safes from xss
    },
  });

export default i18n;
